cache.size: 5
cache.algorithm: LFU

print.output.type: console
print.base.url: D://check-gradle/receipts/
print.pdf.background: https://github.com/stebadmitriy/files/raw/main/Clevertec_Template.pdf
print.pdf.filename.format: receipt-%d-%s-%d.pdf
print.txt.filename.format: receipt-%d-%s-%d.txt